name: Rust

on:
  push:
    branches: [ "main", "sso" ]
  pull_request:
    branches: [ "main", "sso" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run 
      run: cargo run
    # - name: Run tests
    #   run: cargo test --verbose  
